name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yaml
    with:
      result-artifact-url: ${{ needs.build.outputs.artifact-url }}
